### ISSUE TITLE
Cannot find some of the files

### ISSUE THREAD

**Issue by KasparPeterson** [Priberam/TurboTextAnalysis#1]
Hello, thanks for the great work!

However I could not find some of the files that the python test.py uses.
Could you please point out where to get the following files:
        
    filepath_abbreviations = "english_abbreviations.txt";
    filepath_contractions = "english_contractions.txt";
    filepath_contraction_suffixes = "english_contraction_suffixes.txt";
    filepath_lemmas = "english_lemmas.txt";
        
    filepath_morphological_tagger_model = "english_morphological_tagger.model";
    filepath_entity_recognizer_model = "english_entity_recognizer.model";
    filepath_semantic_parser_model = "english_semantic_parser.model";
    filepath_coreference_resolver_model = "english_coreference_resolver.model";

**Comment by smiranda** [comment]
Hello @KasparPeterson,
We're not distributing those auxiliary and pretrained model files here in our fork,

Have you checked the main repository here https://github.com/andre-martins/TurboParser ? If you need any help please also open the issue there.

**Comment by KasparPeterson** [comment]
Thanks for the quick response.

I have checked the main repository and downloaded everything that I found from here: https://www.cs.cmu.edu/~ark/TurboParser/

I found only:
* english_proj_tagger.model
* english_proj_parser.model

Can you please give some idea where do find:
* these .txt files
* english_morphological_tagger.model
* english_entity_recognizer.model
* english_semantic_parser.model
* english_coreference_resolver.model

Cannot seem to find these files anywhere.

**Comment by smiranda** [comment]
Hello @KasparPeterson we don't distribute these pretrained models here (I also searched for them elsewhere and couldn't find them) because this repo is just a fork for our own software integration. So I cannot guarantee the tests/samples/etc work. Please file this issue in the main repo where the people working on this may help you.
